### ISSUE TITLE
bug: missing dependencies

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/langchain-serve#26]
Running `lc-serve deploy babagi` on Python 3.10 returns following:

```
Could not find module lcserve.apps.babyagi.app
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<babyagi() done, defined at /mnt/data/work/sandbox/lc-serve-test/env/lib/python3.10/site-packages/lcserve/__main__.py:170> exception=SystemExit(1)>
Traceback (most recent call last):
  File "/mnt/data/work/sandbox/lc-serve-test/env/lib/python3.10/site-packages/lcserve/flow.py", line 183, in push_app_to_hubble
    app = import_module(mod)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/data/work/sandbox/lc-serve-test/env/lib/python3.10/site-packages/lcserve/apps/babyagi/app.py", line 7, in <module>
    from babyagi import BabyAGI, CustomTool, PredefinedTools, get_tools, get_vectorstore
  File "/mnt/data/work/sandbox/lc-serve-test/env/lib/python3.10/site-packages/lcserve/apps/babyagi/babyagi.py", line 5, in <module>
    import faiss
ModuleNotFoundError: No module named 'faiss'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/work/sandbox/lc-serve-test/env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/mnt/data/work/sandbox/lc-serve-test/env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/data/work/sandbox/lc-serve-test/env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/data/work/sandbox/lc-serve-test/env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/data/work/sandbox/lc-serve-test/env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/data/work/sandbox/lc-serve-test/env/lib/python3.10/site-packages/lcserve/flow.py", line 31, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/mnt/data/work/sandbox/lc-serve-test/env/lib/python3.10/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
  File "/mnt/data/work/sandbox/lc-serve-test/env/lib/python3.10/site-packages/nest_asyncio.py", line 84, in run_until_complete
    self._run_once()
  File "/mnt/data/work/sandbox/lc-serve-test/env/lib/python3.10/site-packages/nest_asyncio.py", line 120, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/mnt/data/work/sandbox/lc-serve-test/env/lib/python3.10/site-packages/nest_asyncio.py", line 196, in step
    step_orig(task, exc)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/mnt/data/work/sandbox/lc-serve-test/env/lib/python3.10/site-packages/lcserve/__main__.py", line 214, in babyagi
    await serve_babyagi_on_jcloud(
  File "/mnt/data/work/sandbox/lc-serve-test/env/lib/python3.10/site-packages/lcserve/__main__.py", line 76, in serve_babyagi_on_jcloud
    await serve_on_jcloud(
  File "/mnt/data/work/sandbox/lc-serve-test/env/lib/python3.10/site-packages/lcserve/__main__.py", line 44, in serve_on_jcloud
    gateway_id_wo_tag, is_websocket = push_app_to_hubble(
  File "/mnt/data/work/sandbox/lc-serve-test/env/lib/python3.10/site-packages/lcserve/flow.py", line 192, in push_app_to_hubble
    sys.exit(1)
SystemExit: 1
```

**Comment by zac-li** [comment]
Please upgrade (`pip install -U langchain-serve`) and retry, thanks for reporting!
